## Домашнее задание 1 (5 баллов)

Все задания ниже имеют равный вес (5/10).

### О задании

В этом домашнем задании вы попрактикуетесь в работе с библиотекой numpy, которая позволяет сравнительно легко и удобно выполнять разнообразные вычисления, избегая самостоятельной реализации поэлементной обработки.

Во всех задачах необходимо написать код решения внутри функции и убедиться, что она работает, с помощью [assert](https://python-reference.readthedocs.io/en/latest/docs/statements/assert.html) на выражение с использованием этой функции для данных из условия.

При решении задач запрещается использовать циклы (`for`, `while`) и оператор `if`. Да, `map`, `reduce`, `filter` и любые другие "чисто питоновские" конструкции тоже запрещены. **Используйте только функционал numpy**.

Везде, где встречаются массивы или матрицы, подразумевается, что это `numpy.array`.

**numpy reference:** https://numpy.org/doc/stable/reference/index.html

In [2]:
import numpy as np

### Задание 1

Напишите функцию, возвращающую округленную взвешенную сумму оценок по данным оценкам и весам. Можете посчитать свою оценку за курс :) В нашем случае вес экзамена равен 0.3, вес домашек - 0.4, вес контрольной - 0.2, вес самостоятельных - 0.1. Например, если за экзамен у вас 7, за домашки 10, за контрольную 8, а за самостоятельные 6, то вы получите отличную оценку 8!

Обратите внимание, что на вход приходит всегда двумерный массив. В нем в каждой строке - окенки одного конкретного студента. От вас требуется вернуть итоговую оценку для всех студентов в массиве.

In [3]:
def result_mark(weights: np.array, marks: np.array) -> int:
    mat = np.matmul(marks, weights)
    return mat.round()

In [4]:
weights = np.array([0.3, 0.4, 0.2, 0.1])
marks = np.array([[7, 10, 8, 6], [6, 9, 7, 6]])

assert np.allclose(result_mark(weights, marks), np.array([8, 7]))

In [5]:
weights = np.array([0.3, 0.4, 0.2, 0.1])
marks = np.array([[7, 0, 8, 6]])

assert np.allclose(result_mark(weights, marks), np.array([4]))

### Задание 2

Напишите функцию, которая каждое четное число в массиве заменяет на его квадрат (вторую степень), а нечетное - на его синус. Округлите все значения в итоговом массиве до двух знаков после запятой.

In [6]:
a = np.linspace(0, 10, 3).astype("int")
print(a)
np.sin(a)

[ 0  5 10]


array([ 0.        , -0.95892427, -0.54402111])

In [7]:
def change_array(array: np.array) -> np.array:
    array = array.astype("float")
    array[array % 2 == 0] = array[array % 2 == 0] ** 2
    array[array % 2 == 1] = np.sin(array[array % 2 == 1])
    return array.round(2)

array = np.array([2, 5, 1, 0, -6, 22, 213431])
array[array % 2 == 0]
change_array(array)

array([  4.  ,  -0.96,   0.84,   0.  ,  36.  , 484.  ,  -0.58])

In [8]:
array = np.array([2, 5, 1, 0, -6, 22, 213431])

assert np.allclose(change_array(array), np.array([4.0, -0.96, 0.84, 0.0, 36.0, 484.0, -0.58]))

In [9]:
array = np.array([3, 12, 15, -97, 6])

assert np.allclose(change_array(array), np.array([0.14, 144.0, 0.65, -0.38, 36.0]))

### Задание 3

Напишите функцию, которая вычисляет разность каждого элемента с предыдущим (для самого первого считайте, что его разница с "предыдущим" нулевая) в виде нового массива и возвращает вектор, в котором каждый новый элемент - сумма всех предыдущих из полученного нового массива.

In [10]:
def cumulative_sum_of_differences(array):
    diff = array - np.hstack((np.array(0), array[:-1]))
    diff[0] = 0
    return np.cumsum(diff)

In [11]:
array = np.array([3, 6, 2, 8])

assert np.allclose(cumulative_sum_of_differences(array), np.array([0, 3, -1, 5]))

In [12]:
array = np.array([5, 1])

assert np.allclose(cumulative_sum_of_differences(array), np.array([0, -4]))

### Задание 4

Напишите функцию, которая транспонирует двумерный массив, затем делает из него одномерный (reshape), переводит все элементы массива в *int8* и выводит его отсортированным по убыванию.

In [13]:
def flatten_and_sort_transposed(array: np.array) -> np.array:
    array = array.astype("int8")
    vec = np.sort(np.reshape(array, (-1)))
    return vec[::-1]

array = np.array(
    [
        [256, -10],
        [-381, 112],
    ]
)
flatten_and_sort_transposed(array)

array([ 112,    0,  -10, -125], dtype=int8)

In [14]:
array = np.array(
    [
        [256, -10],
        [-381, 112],
    ]
)

assert np.allclose(flatten_and_sort_transposed(array), np.array([112, 0, -10, -125]))

In [15]:
array = np.array([[9, 8, 7], [3, 6, 129]])

assert np.allclose(flatten_and_sort_transposed(array), np.array([ 9, 8, 7, 6, 3, -127]))

### Задание 5

Напишите функцию, которая удаляет из массива все строки, среднее значение в которых больше общего среднего значения по всему массиву.

In [16]:
def filter_rows_by_mean(array):
    mean = np.mean(array)
    idx = np.mean(array, axis=1) <= mean
    return array[idx]

array = np.array([[1, 2, 3], [7, 8, 9], [4, 5, 6]])
res = filter_rows_by_mean(array)
res

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
array = np.array([[1, 2, 3], [7, 8, 9], [4, 5, 6]])
res = filter_rows_by_mean(array)

assert res.ndim == 2
assert np.allclose(res, np.array([[1, 2, 3], [4, 5, 6]]))

In [18]:
array = np.array([[10, 20], [5, 5], [15, 15]])
res = filter_rows_by_mean(array)

assert res.ndim == 2
assert np.allclose(res, np.array([[5, 5]]))

### Задание 6

Напишите функцию, которая принимает на вход число - размер массива (квадратная матрица), который заполнен по принипу щахматной доски нулями и единицами. Первой (слева сверху) идет всегда единица. Напомним, что на шахматной доске белые и черные ячейки чередуются (в данном задании чередуются нули и единицы).

In [19]:
def create_checkerboard(number):
    desk = np.zeros((number, number)).astype("int8")
    desk[::2, ::2] = 1
    desk[1::2, 1::2] = 1
    return desk

number = 4
create_checkerboard(number)

array([[1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1]], dtype=int8)

In [20]:
number = 3

assert np.allclose(create_checkerboard(number) - np.array([[1, 0, 1], [0, 1, 0], [1, 0, 1]]), np.zeros((number, number)))

In [21]:
number = 4

assert np.allclose(create_checkerboard(number) - np.array([[1, 0, 1, 0], [0, 1, 0, 1], [1, 0, 1, 0], [0, 1, 0, 1]]), np.zeros((number, number)))

### Задание 7

Напишите функцию, которая соритрует строки двумерного массива по значению в первом (начиная с нуля) столбце (по возрастанию).

In [22]:
np.sort?

Signature:       np.sort(a, axis=-1, kind=None, order=None)
Call signature:  np.sort(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sort at 0x1176ea340>
File:            /opt/miniconda3/lib/python3.12/site-packages/numpy/core/fromnumeric.py
Docstring:      
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of str,

In [23]:
def sort_rows_by_second_column(array):
    first_column = array[::, 1:2:].reshape((-1))
    idx = np.argsort(first_column)
    return array[idx]

array = np.array([[10, 2], [3, 5], [7, 1]])
sort_rows_by_second_column(array)

array([[ 7,  1],
       [10,  2],
       [ 3,  5]])

In [24]:
array = np.array([[10, 2], [3, 5], [7, 1]])

assert np.allclose(sort_rows_by_second_column(array), np.array([[7, 1], [10, 2], [3, 5]]))

In [25]:
array = np.array([[5, 8, 1], [10, 3, 9], [2, 7, 0], [6, -1, 5]])

assert np.allclose(sort_rows_by_second_column(array), np.array([[6, -1, 5], [10, 3, 9], [2, 7, 0], [5, 8, 1]]))

### Задание 8

Напишите функцию, которая вычисляет сумму элементов [побочной](https://ru.wikipedia.org/wiki/Квадратная_матрица) диагонали квадратной матрицы.

In [26]:
def sum_counterdiagonal_elements(array):
    return array[::-1].trace()

array = np.array([[5, 8, 1], [10, 3, 9], [2, 7, 0]])
sum_counterdiagonal_elements(array)

6

In [27]:
array = np.array([[5, 8, 1], [10, 3, 9], [2, 7, 0]])

assert sum_counterdiagonal_elements(array) == 6

In [28]:
array = np.array([[-4, -1, -1, 7], [6, -10, 5, -9], [3, -8, 6, 8], [-1, -6, 7, -10]])

assert sum_counterdiagonal_elements(array) == 3

### Задание 9

Напишите функцию, которая принимает на вход три числа (начало отрезка, конец отрезка, количество точек на отрезке). Данная функция генерирует указанное количество точек равномерно на отрезке с указанными концами (точки равноудалены друг от друга). Затем функция генерирует другой массив - натуральный логарифм от всех точек отрезка плюс единица ($ln(point + 1)$). Возвращает функция массив пар точек вида (точка на отрезке, ее логарифм). Каждое значение в возвращаемом массиве должно быть округлено до двух знаков после запятой.

In [29]:
def generate_logarithm_points(start, end, count):
    lsp = np.linspace(start, end, count)
    ln = np.log(lsp + 1)
    dots = np.column_stack([lsp, ln])
    return dots.round(2)

In [30]:
start = 1
end = 10
count = 5

assert np.allclose(generate_logarithm_points(start, end, count), np.array([[1., 0.69], [3.25, 1.45], [5.5 , 1.87], [7.75, 2.17], [10., 2.4]]))

In [31]:
start = 5
end = 12
count = 4

assert np.allclose(generate_logarithm_points(start, end, count), np.array([[5., 1.79], [7.33, 2.12], [9.67, 2.37], [12., 2.56]]))

### Задание 10

Напишите функцию, которая нормализует входной двумерный массив. 

Под нормализацией в данном задании подразумевается перевод всех чисел массива на отрезок $[0; 1]$. Очевидно, недостаточно просто вычесть/прибавить лишнее, чтобы остались числа на нужном отрезке. Суть нормализации массива в том, чтобы не потерять информацию о его элементах и их соотношениях. Потому, необходимо сохранить пропорции расстояний между каждым числом - спроецировать все точки на указанный отрезок. Такой метод масштабирования массива называется MinMaxScaling. Само название дает подсказку, как нужно решить задачу. Дробные числа округляйте до двух знаков после запятой.

*Будьте осторожны с делением...*

In [32]:
def min_max_scale(array):
    mi = np.min(array)
    ma = np.max(array)
    try:
        array = (array - mi) / (ma - mi)
        return array.round(2)
    except ZeroDivisionError as e:
        return np.zeros(array.shape)
    

In [33]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

assert np.allclose(min_max_scale(array), np.array([[0. , 0.12, 0.25], [0.38, 0.5 , 0.62], [0.75, 0.88, 1.]]))

In [34]:
array = np.array([[1, 1, 1], [3, 4, 5]])

assert np.allclose(min_max_scale(array), np.array([[0., 0.2, 0.4], [0.6, 0.8, 1.]]))

AssertionError: 