In [1]:
a = 10
b = 20
a + b


30

In [3]:
import numpy as np

In [9]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
arr.dtype

dtype('int64')

In [11]:
type(arr)

numpy.ndarray

In [12]:
arr.shape

(3, 2)

In [13]:
arr.ndim

2

n=1 - вектор, n=2 - тензор, n>=3 - тензор

In [14]:
np.sum(arr)

21

In [15]:
np.sum(arr, axis=0)

array([ 9, 12])

In [16]:
np.sum(arr, axis=1)

array([ 3,  7, 11])

In [17]:
arr.reshape(2, 3, 1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [18]:
arr.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
arr[:, 1]

array([2, 4, 6])

In [21]:
arr[2, :]

array([5, 6])

In [22]:
arr[0:1, 1:2]

array([[2]])

In [23]:
arr + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [24]:
arr ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [25]:
np.sin(arr)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

In [26]:
arr.dot(vec ** 2)

NameError: name 'vec' is not defined

In [29]:
is_even = arr % 2 == 0
is_even

array([[False,  True],
       [False,  True],
       [False,  True]])

In [30]:
np.sum(is_even)

3

In [33]:
arr[arr % 2 == 0]

array([2, 4, 6])

In [35]:
# hstack, vstack

In [37]:
np.random.rand(2, 3)

array([[0.68181913, 0.71705446, 0.22886408],
       [0.34436545, 0.88341887, 0.41230854]])

In [42]:
np.random.seed(27012025)
np.random.rand(2, 3)

array([[0.70066916, 0.64456938, 0.08327351],
       [0.74478659, 0.25750138, 0.59850581]])

In [ ]:
from tqdm import tqdm

In [49]:
# task1
arr = np.arange(10)
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [62]:
# task2
arr = np.arange(100)

# arr = np.sort(arr)
arr = arr[::-1]
arr[arr % 2 == 1].max()

99

In [56]:
# task3
arr = np.arange(100)
arr[arr % 2 == 1] = 666



array([  0, 666,   2, 666,   4, 666,   6, 666,   8, 666,  10, 666,  12,
       666,  14, 666,  16, 666,  18, 666,  20, 666,  22, 666,  24, 666,
        26, 666,  28, 666,  30, 666,  32, 666,  34, 666,  36, 666,  38,
       666,  40, 666,  42, 666,  44, 666,  46, 666,  48, 666,  50, 666,
        52, 666,  54, 666,  56, 666,  58, 666,  60, 666,  62, 666,  64,
       666,  66, 666,  68, 666,  70, 666,  72, 666,  74, 666,  76, 666,
        78, 666,  80, 666,  82, 666,  84, 666,  86, 666,  88, 666,  90,
       666,  92, 666,  94, 666,  96, 666,  98, 666])

In [63]:
# task4
n = 5
arr = np.arange(2*n+1)
arr_odd = arr[arr % 2 == 1]

arr_odd[::-1]

array([9, 7, 5, 3, 1])

In [77]:
# task5
n = 100
k = 33.3
arr = np.arange(n)

max_n = arr[np.argmax(abs(arr - k))]
print(max_n)

min_n = arr[np.argmin(abs(arr - k))]
min_n

99


33

In [81]:
# task6

def f(x):
    return 4*x**3+6*x**2+1

f(np.array([1, 2, 3]))

array([ 11,  57, 163])

In [83]:
help(len)


Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [84]:
def sq(a):
    """Return the square of a."""
    return a**2

In [85]:
sq?

Signature: sq(a)
Docstring: Return the square of a.
File:      /var/folders/bc/z2tbr02j71z_j79b47m1vkp80000gn/T/ipykernel_25693/2513441892.py
Type:      function

In [86]:
sq??

Signature: sq(a)
Source:   
def sq(a):
    """Return the square of a."""
    return a**2
File:      /var/folders/bc/z2tbr02j71z_j79b47m1vkp80000gn/T/ipykernel_25693/2513441892.py
Type:      function

In [88]:
str.find?


Docstring:
S.find(sub[, start[, end]]) -> int

Return the lowest index in S where substring sub is found,
such that sub is contained within S[start:end].  Optional
arguments start and end are interpreted as in slice notation.

Return -1 on failure.
Type:      method_descriptor

In [89]:
%%timeit
def f():
    a = 0
    for i in range(100_000):
        a += i ** 2


74.6 ns ± 1.38 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [92]:
a = np.ones((2, 3))
b = np.arange(3)
a + b

array([[1., 2., 3.],
       [1., 2., 3.]])